# config/patch_sh/config.yml
# tag
version_format: "{major}.{minor}.{patch}" # 定义标签格式
major: 1
minor: 1
patch: 110
update: "patch" # 可选值: major, minor, patch
release_notes: |
  - 修复了一些已知问题。
  - 优化了性能表现。
  - 新增功能 A 和功能 B。
# kk =
custom_command_wakeup: kk
