name: Rollback to previous commit

on:
  # 手动触发
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出当前仓库代码
      - name: Checkout this repository
        uses: actions/checkout@v3

      # Step 2: 回退到上一次提交
      - name: Revert to previous commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git reset --hard HEAD~1
          git push --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
