name: Sync Kejilion SH

on:
  push:
    branches:
      - main  # 自动触发在主分支上的 push 操作
      
  workflow_dispatch:  # 支持手动触发

jobs:
  sync_sh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Delete existing kejilion/sh directory
        run: |
          rm -rf kejilion/sh  # 删除本地目录，避免冲突

      - name: Pull latest changes from remote main
        run: |
          git pull origin main  # 拉取远程 main 分支的最新内容

      - name: Clone the Kejilion/sh repository
        run: |
          git clone https://github.com/kejilion/sh.git kejilion/sh  # 克隆最新内容到本地目录

      - name: Commit and push the changes
        run: |
          git add kejilion/sh  # 添加更新后的 kejilion/sh 目录
          git commit -m "Sync with Kejilion/sh repository" || git commit --amend --no-edit --allow-empty -m "Sync with Kejilion/sh repository"
          git push origin main  # 推送到远程仓库
