name: Sync Kejilion/sh to own repository

on:
  push:
    branches:
      - main  # 可以指定你希望监听的分支，如 main 或其他分支
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    
    - name: Delete existing sh directory content
      run: |
        if [ -d "kejilion/sh" ]; then
          rm -rf kejilion/sh/*  # 删除文件夹中的内容
        else
          mkdir -p kejilion/sh  # 如果文件夹不存在就创建
        fi
    
    - name: Clone the remote repository
      run: |
        git clone --depth 1 https://github.com/kejilion/sh.git kejilion/sh
    
    - name: Commit and push changes
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"
        git add kejilion/sh
        git commit -m "Sync kejilion/sh to the repository"
        git push origin main  # 可以调整为合适的分支
