name: Clone Kejilion SH Repo

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Git branch to clone'
        required: false
        default: 'main'

jobs:
  clone-and-update:
    runs-on: ubuntu-latest
    steps:
      # 检出当前仓库的代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 删除目标文件夹内容
      - name: Remove old directory contents
        run: |
          rm -rf ./kejilion/sh
          mkdir -p ./kejilion/sh

      # 克隆远程仓库到指定目录
      - name: Clone Kejilion SH Repo
        run: |
          git clone --single-branch --branch main https://github.com/kejilion/sh.git ./kejilion/sh

      # 删除 `.git` 文件夹，以避免被当作子模块
      - name: Remove .git from the cloned repository
        run: |
          rm -rf ./kejilion/sh/.git

      # 提交更改到当前仓库
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update kejilion/sh content" || echo "No changes to commit"
          git push
