name: Sync kejilion/sh to this repository

on:
  # 定时任务：每天凌晨 1 点触发
  schedule:
    - cron: '0 1 * * *'
  # 手动触发
  workflow_dispatch:

jobs:
  clone-and-sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出当前仓库代码
      - name: Checkout this repository
        uses: actions/checkout@v3

      # Step 2: 清理目标目录（如果存在）
      - name: Clean target directory
        run: |
          if [ -d "./kejilion/sh" ]; then
            rm -rf ./kejilion/sh
          fi

      # Step 3: 克隆 kejilion/sh 仓库
      - name: Clone kejilion/sh repository
        run: |
          git clone https://github.com/kejilion/sh.git ./kejilion/sh

      # Step 4: 检查并提交更改（如果有）
      - name: Check for changes and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./kejilion/sh
          if ! git diff --cached --quiet; then
            git commit -m "Synced kejilion/sh repository to kejilion/sh folder"
            git push --force
          else
            echo "No changes to commit"
          fi

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
