name: Clone Kejilion SH Repo

on:
  push:
    branches:
      - main   # 你可以根据需求更改为你想要触发的分支
  workflow_dispatch:   # 手动触发
    inputs:
      branch:
        description: 'Git branch to clone'
        required: false
        default: 'main'

jobs:
  clone-and-update:
    runs-on: ubuntu-latest
    steps:
      # 检出当前仓库的代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 删除目标文件夹内的内容
      - name: Remove old directory contents
        run: |
          echo "Removing old directory contents"
          rm -rf ./kejilion/sh

      # 克隆 kejilion/sh 仓库到指定目录
      - name: Clone Kejilion SH Repo
        run: |
          echo "Cloning repository"
          git clone --single-branch --branch main https://github.com/kejilion/sh.git ./kejilion/sh
          ls -al ./kejilion/sh  # 列出目录内容，确认是否正确克隆

      # 提交更改到当前仓库（如果有变化）
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update kejilion/sh content" || echo "No changes to commit"
          git push origin main  # 确保推送到正确的分支
