name: Sync Kejilion SH

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 支持手动触发

jobs:
  sync_sh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Delete existing kejilion/sh directory
        run: |
          rm -rf kejilion/sh

      - name: Clone the Kejilion/sh repository
        run: |
          git clone https://github.com/kejilion/sh.git kejilion/sh
        continue-on-error: true  # 如果克隆失败时不要阻止后续步骤

      - name: Check if cloning was successful
        run: |
          if [ ! -d "kejilion/sh" ]; then
            echo "Error: Cloning failed. Exiting."
            exit 1
          fi
          echo "Cloning was successful"

      - name: Debugging - Show changes
        run: |
          git status

      - name: Force add kejilion/sh directory
        run: |
          git add -f kejilion/sh
          git status

      - name: Commit and push the changes
        run: |
          git commit -m "Sync with Kejilion/sh repository" || echo "No changes to commit"
          git push origin main
