name: Sync Kejilion SH Repo

on:
  push:
    branches:
      - main  # 自动触发的分支
  workflow_dispatch:  # 支持手动触发

jobs:
  sync_repo:
    runs-on: ubuntu-latest
    
    steps:
      # 第一步：检查出自己的代码仓库
      - name: Checkout own repository
        uses: actions/checkout@v3
        
      # 第二步：删除目标目录，确保目录为空
      - name: Delete existing kejiion/sh folder
        run: rm -rf kejiion/sh

      # 第三步：克隆远程仓库内容到目标目录
      - name: Clone remote repository to target directory
        run: |
          git clone --depth 1 https://github.com/kejilion/sh.git kejiion/sh
          
      # 第四步：删除 kejiion/sh/.git 以避免被识别为子模块
      - name: Remove .git to prevent submodule detection
        run: rm -rf kejiion/sh/.git

      # 第五步：提交并推送更改
      - name: Commit and push changes
        run: |
          git config user.name "Your Name"
          git config user.email "youremail@example.com"
          git add .
          git commit -m "Sync with remote kejilion/sh repository"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动化提交需要权限，可以通过 GitHub Token 来授权
